### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by HarvestWinter** [OmnigamerSDA/Sui2StatsChecker#1]
Hello! Are you still active here?

**Comment by OmnigamerSDA** [comment]
I am when necessary. Please only submit issues when there is an actual issue to resolve.

**Comment by HarvestWinter** [comment]
Sorry to bother. Do you know how to mod Riou battler to other characters something like this? Please help.
https://www.youtube.com/watch?v=Hg0rf9-PqK8
